#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Linux 3.10.7 vbox' {
    insmod ext2
    linux   /boot/bzImage-3.10.6 root=/dev/sda1 ro
}

menuentry 'Linux 3.10.7-stage1 vbox' {
    insmod ext2
    linux   /boot/bzImage-3.10.7-stage1 root=/dev/sda1 ro
}

menuentry 'Linux 3.10.7-stage2 vbox' {
    insmod ext2
    linux   /boot/bzImage-3.10.7-stage2 root=/dev/sda1 ro vga=791 quiet
}
